name: Create Artifact

on: [push]

jobs:
  create_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create text file with content
        run: echo "${{ secrets.NOTE }}" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: simple-artifact
          path: hello.txt
