name: Create Encrypted Artifact

on: [push]

jobs:
  create_encrypted_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store the secret value in a file
        run: |
          echo "${{ secrets.NOTE }}" > secret.txt

      - name: Encrypt the secret file
        run: |
          gpg --batch --yes --symmetric --cipher-algo AES256 --output secret.txt.gpg --passphrase "${{ secrets.GPG_PASSPHRASE }}" secret.txt

      - name: Upload encrypted artifact
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-secret
          path: secret.txt.gpg
