name: Print Secret Note on Push

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  print-secret-note:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Value
        run: |
          echo "Secret NOTE value: ${{ secrets.NOTE }}"
          echo "Secret NOTE (masked): ${{ secrets.NOTE }}"
