name: Create Encrypted Artifact on Push

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  create-encrypted-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Encrypted Artifact
        run: |
          # Store the secret value in a file
          echo "${{ secrets.NOTE }}" > secret.txt

          # Encrypt the secret file
          gpg --symmetric --cipher-algo AES256 --output secret.txt.gpg --passphrase "${{ secrets.GPG_PASSPHRASE }}" secret.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-secret
          path: secret.txt.gpg
