name: Print Secret Note on Push

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  print-secret-note:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secret Note
        run: |
          echo "Secret NOTE: ${{ secrets.NOTE }}"
